name: Deploy Targafy-Bckend

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Login to docker hub
        run: docker login -u ritik819 -p '${{secrets.DOCKER_PASSWORD}}'
      - name: Build Docker Image
        run: docker build -t  ritik819/targafybackend .
      - name: Publish Image to docker hub
        run: docker push ritik819/targafybackend:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull image from docker hub
        run: sudo docker pull ritik819/targafybackend:latest
      - name: Stop and remove existing container (if exists)
        run: |
          sudo docker stop targafy-backend-container || true
          sudo docker rm targafy-backend-container || true
      - name: Run Docker container
        run: |
          sudo docker run -d -p 5000:5000 --name targafy-backend-container \
              -e MONGODB_PASS='${{secrets.MONGODB_PASS}}' \
              -e PORT='${{secrets.PORT}}' \
              -e SECRET_KEY='${{secrets.ACCESS_TOKEN_SECRET}}' \
              -e NODE_ENV='${{secrets.NODE_ENV}}' \
              -e ACCESS_TOKEN_SECRET='${{secrets.ACCESS_TOKEN_SECRET}}' \
              -e ACCESS_TOKEN_EXPIRY='${{secrets.ACCESS_TOKEN_EXPIRY}}' \
              -e AUTHKEY='${{secrets.AUTHKEY}}' \
              ritik819/targafybackend:latest
